cartoons=['tom&jerry','krishna aur balram','chotabheem','dora','shinchan','ben_ten']
print(cartoons)
print("after appending an element:")
cartoons.append('oggy&cockroaches')
print(cartoons)
print("after inserting the elements:")
cartoons.insert(2,'roll number 21')
print(cartoons)
print("after popping the element:")
cartoons.pop()
print(cartoons)
cartoons.pop(4)
print(cartoons)
cartoons.remove('chotabheem')
print(cartoons)
print(cartoons.index('tom&jerry'))
print("after reversing the list:")
cartoons.reverse()
print(cartoons)
