Num=[11,22,33,44,55,66,77,88,99,100]
print(Num)
print("--------------------")
Num[0]=111
print(Num)
print("--------------------")
Num[1]=222
print(Num)
print("--------------------")
Num[2]=333
print(Num)
print("----------------------")
Num[3]=444
print(Num)
print("--------------------")
Num[4]=555
print(Num)
print("--------------------")
Num[5]=666
print(Num)
print("--------------------")
Num[6]=777
print(Num)
print("--------------------")
Num[7]=888
print(Num)
print("--------------------")
Num[8]=999
print(Num)
print("--------------------")
Num[9]=1000
print(Num)
print("----------------------")

